//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Planner_V_4.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daily_Planner_V_4.Properties.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Group.
        /// </summary>
        public static string Add_Grp_Btn {
            get {
                return ResourceManager.GetString("Add_Grp_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color of new group :.
        /// </summary>
        public static string Add_Grp_Wndw__Choose_Color {
            get {
                return ResourceManager.GetString("Add_Grp_Wndw__Choose_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Group Name :.
        /// </summary>
        public static string Add_Grp_Wndw__Enter_Grp_Name {
            get {
                return ResourceManager.GetString("Add_Grp_Wndw__Enter_Grp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Btn {
            get {
                return ResourceManager.GetString("Cancel_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgently.
        /// </summary>
        public static string ChkBx_Urgently_Content {
            get {
                return ResourceManager.GetString("ChkBx_Urgently_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Btn {
            get {
                return ResourceManager.GetString("Close_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete task.
        /// </summary>
        public static string Complete_Task_Btn {
            get {
                return ResourceManager.GetString("Complete_Task_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete_Task_Btn_Short {
            get {
                return ResourceManager.GetString("Complete_Task_Btn_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Task Completed?.
        /// </summary>
        public static string Complete_Task_request_Window_String {
            get {
                return ResourceManager.GetString("Complete_Task_request_Window_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!   Task Completed   !!!.
        /// </summary>
        public static string Completed_Note_String {
            get {
                return ResourceManager.GetString("Completed_Note_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create Note.
        /// </summary>
        public static string Create_Note_Btn {
            get {
                return ResourceManager.GetString("Create_Note_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Days_Friday {
            get {
                return ResourceManager.GetString("Days_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Days_Monday {
            get {
                return ResourceManager.GetString("Days_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Days_Saturday {
            get {
                return ResourceManager.GetString("Days_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string Days_Short_Friday {
            get {
                return ResourceManager.GetString("Days_Short_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string Days_Short_Monday {
            get {
                return ResourceManager.GetString("Days_Short_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string Days_Short_Saturday {
            get {
                return ResourceManager.GetString("Days_Short_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string Days_Short_Sunday {
            get {
                return ResourceManager.GetString("Days_Short_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string Days_Short_Thursday {
            get {
                return ResourceManager.GetString("Days_Short_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string Days_Short_Tuesday {
            get {
                return ResourceManager.GetString("Days_Short_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string Days_Short_Wednesday {
            get {
                return ResourceManager.GetString("Days_Short_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Days_Sunday {
            get {
                return ResourceManager.GetString("Days_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Days_Thursday {
            get {
                return ResourceManager.GetString("Days_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Days_Tuesday {
            get {
                return ResourceManager.GetString("Days_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Days_Wednesday {
            get {
                return ResourceManager.GetString("Days_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default_string {
            get {
                return ResourceManager.GetString("Default_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group within all notes?.
        /// </summary>
        public static string Delete_Grp_Request {
            get {
                return ResourceManager.GetString("Delete_Grp_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Note_Btn {
            get {
                return ResourceManager.GetString("Delete_Note_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete note?.
        /// </summary>
        public static string Delete_Note_Request {
            get {
                return ResourceManager.GetString("Delete_Note_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Note_Btn {
            get {
                return ResourceManager.GetString("Edit_Note_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string En_lang {
            get {
                return ResourceManager.GetString("En_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Header.......
        /// </summary>
        public static string Enter_Header_string {
            get {
                return ResourceManager.GetString("Enter_Header_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegated.
        /// </summary>
        public static string Executor_string_Delegated {
            get {
                return ResourceManager.GetString("Executor_string_Delegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Executor_string_Me {
            get {
                return ResourceManager.GetString("Executor_string_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!   Expired   !!!.
        /// </summary>
        public static string Expired_string {
            get {
                return ResourceManager.GetString("Expired_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegated Tasks.
        /// </summary>
        public static string Group_of_Delegated_Notes {
            get {
                return ResourceManager.GetString("Group_of_Delegated_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string Group_of_My_Notes {
            get {
                return ResourceManager.GetString("Group_of_My_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That group os already exist. Choose another group name.
        /// </summary>
        public static string Grp_Name_Already_Exist_Error_Msg {
            get {
                return ResourceManager.GetString("Grp_Name_Already_Exist_Error_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide_Note_Btn {
            get {
                return ResourceManager.GetString("Hide_Note_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language will change after restart program.
        /// </summary>
        public static string Language_Change_Message {
            get {
                return ResourceManager.GetString("Language_Change_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing language.
        /// </summary>
        public static string Language_Change_Window_Name {
            get {
                return ResourceManager.GetString("Language_Change_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add frome file....
        /// </summary>
        public static string Menu_Add_From_File_String {
            get {
                return ResourceManager.GetString("Menu_Add_From_File_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Menu_Info {
            get {
                return ResourceManager.GetString("Menu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_Open_String {
            get {
                return ResourceManager.GetString("Menu_Open_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save_String {
            get {
                return ResourceManager.GetString("Menu_Save_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_Settings_Language {
            get {
                return ResourceManager.GetString("Menu_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu_String {
            get {
                return ResourceManager.GetString("Menu_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Monthes_April {
            get {
                return ResourceManager.GetString("Monthes_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Monthes_August {
            get {
                return ResourceManager.GetString("Monthes_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Monthes_December {
            get {
                return ResourceManager.GetString("Monthes_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Monthes_February {
            get {
                return ResourceManager.GetString("Monthes_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Monthes_January {
            get {
                return ResourceManager.GetString("Monthes_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Monthes_July {
            get {
                return ResourceManager.GetString("Monthes_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Monthes_June {
            get {
                return ResourceManager.GetString("Monthes_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Monthes_March {
            get {
                return ResourceManager.GetString("Monthes_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Monthes_May {
            get {
                return ResourceManager.GetString("Monthes_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Monthes_November {
            get {
                return ResourceManager.GetString("Monthes_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Monthes_October {
            get {
                return ResourceManager.GetString("Monthes_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Monthes_September {
            get {
                return ResourceManager.GetString("Monthes_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter executor......
        /// </summary>
        public static string new_note_executor_empty_string {
            get {
                return ResourceManager.GetString("new_note_executor_empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No_Btn {
            get {
                return ResourceManager.GetString("No_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note content.
        /// </summary>
        public static string Note_Content_Btn_string {
            get {
                return ResourceManager.GetString("Note_Content_Btn_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Note_Default_Header {
            get {
                return ResourceManager.GetString("Note_Default_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string note_time_range_1_hour {
            get {
                return ResourceManager.GetString("note_time_range_1_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 min.
        /// </summary>
        public static string note_time_range_10_min {
            get {
                return ResourceManager.GetString("note_time_range_10_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 min.
        /// </summary>
        public static string note_time_range_15_min {
            get {
                return ResourceManager.GetString("note_time_range_15_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min.
        /// </summary>
        public static string note_time_range_30_min {
            get {
                return ResourceManager.GetString("note_time_range_30_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 min.
        /// </summary>
        public static string note_time_range_5_min {
            get {
                return ResourceManager.GetString("note_time_range_5_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Urgent !!!.
        /// </summary>
        public static string Note_Urgency_string {
            get {
                return ResourceManager.GetString("Note_Urgency_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes_Expander_Header {
            get {
                return ResourceManager.GetString("Notes_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app has been minimised. Click the tray icon to show.
        /// </summary>
        public static string NotifyIcon_Minimized_Announce {
            get {
                return ResourceManager.GetString("NotifyIcon_Minimized_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK_Btn {
            get {
                return ResourceManager.GetString("OK_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properities.
        /// </summary>
        public static string Properities_Btn_string {
            get {
                return ResourceManager.GetString("Properities_Btn_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Ru_lang {
            get {
                return ResourceManager.GetString("Ru_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve got trouble during saving data....
        /// </summary>
        public static string Saving_Error_Message {
            get {
                return ResourceManager.GetString("Saving_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search......
        /// </summary>
        public static string Search_string {
            get {
                return ResourceManager.GetString("Search_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Notes:.
        /// </summary>
        public static string Show_Complete_Notes_Btn {
            get {
                return ResourceManager.GetString("Show_Complete_Notes_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Notes:   .
        /// </summary>
        public static string Show_Expired_Notes_Btn {
            get {
                return ResourceManager.GetString("Show_Expired_Notes_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string The_App_Name {
            get {
                return ResourceManager.GetString("The_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         range:.
        /// </summary>
        public static string time_range_string {
            get {
                return ResourceManager.GetString("time_range_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today:   .
        /// </summary>
        public static string Today_Date {
            get {
                return ResourceManager.GetString("Today_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today_String {
            get {
                return ResourceManager.GetString("Today_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorow.
        /// </summary>
        public static string Tomorrow_String {
            get {
                return ResourceManager.GetString("Tomorrow_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Notes:   .
        /// </summary>
        public static string Total_Notes_string {
            get {
                return ResourceManager.GetString("Total_Notes_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who:.
        /// </summary>
        public static string Who_string {
            get {
                return ResourceManager.GetString("Who_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes_Btn {
            get {
                return ResourceManager.GetString("Yes_Btn", resourceCulture);
            }
        }
    }
}
